name: ecfisher
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-271.4.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  enum_to_string: ^2.0.1
  get: ^4.6.5
  http: 
  hive: ^2.2.3
  smooth_page_indicator: ^1.0.0+2
  font_awesome_flutter: ^10.1.0
  motion_tab_bar_v2: ^0.2.6
  animations: ^2.0.3
  woocommerce_api: ^0.1.0
  google_fonts: ^4.0.4
  woosignal: ^3.8.0
  flutter_spinkit: ^5.2.0
  nylo_framework: ^5.1.2
  auto_size_text: ^3.0.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_swiper_view: ^1.1.8
  pull_to_refresh_flutter3: ^2.0.1
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

  # flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/